name: Makefile CI

on:
  push:
    branches: [ "main-woa" ]
  pull_request:
    branches: [ "main-woa" ]

jobs: 
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Install gcc
      run: sudo apt-get install gcc-aarch64-linux-gnu 
      
    - uses: actions/checkout@v4
    - uses: LizardByte/setup-python-action@master
      with:
        python-version: '2.7'
    - name: step1
      run: make -C BaseTools
    - name: step2
      run: source edksetup.sh

    - name: step3
      run: export GCC49_AARCH64_PREFIX=aarch64-linux-gnu-

    - name: step4
      run:  export GCC49_AARCH64_PREFIX=aarch64-linux-gnu-&& export WORKSPACE=/home/runner/work/edk2-woa/edk2-woa && export EDK_TOOLS_PATH=/home/runner/work/edk2-woa/edk2-woa/BaseTools && export CONF_PATH=/home/runner/work/edk2-woa/edk2-woa/Conf && cd ./BaseTools/BinWrappers/PosixLike && export PATH=$PATH:/home/runner/work/edk2-woa/edk2-woa/BaseTools/BinWrappers/PosixLike && ./build -a AARCH64 -t GCC49 -b RELEASE -p ArmVirtPkg/ArmVirtQemu.dsc && cd ../../../
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: QEMU_EFI.fd
        path: ./Build/ArmVirtQemu-AARCH64/RELEASE_GCC49/FV/QEMU_EFI.fd
